/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5CommonModelsCommonDocumentModel from './HelloAssoApiV5CommonModelsCommonDocumentModel';
import HelloAssoApiV5CommonModelsCommonMetaModel from './HelloAssoApiV5CommonModelsCommonMetaModel';
import HelloAssoApiV5CommonModelsCommonPlaceModel from './HelloAssoApiV5CommonModelsCommonPlaceModel';
import HelloAssoApiV5CommonModelsEnumsFormState from './HelloAssoApiV5CommonModelsEnumsFormState';
import HelloAssoApiV5CommonModelsEnumsFormType from './HelloAssoApiV5CommonModelsEnumsFormType';
import HelloAssoApiV5CommonModelsEnumsMembershipValidityType from './HelloAssoApiV5CommonModelsEnumsMembershipValidityType';
import HelloAssoApiV5CommonModelsFormsTierPublicModel from './HelloAssoApiV5CommonModelsFormsTierPublicModel';

/**
 * The HelloAssoApiV5CommonModelsFormsFormPublicModel model module.
 * @module model/HelloAssoApiV5CommonModelsFormsFormPublicModel
 * @version public
 */
class HelloAssoApiV5CommonModelsFormsFormPublicModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsFormsFormPublicModel</code>.
     * FormPublicModel class
     * @alias module:model/HelloAssoApiV5CommonModelsFormsFormPublicModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsFormsFormPublicModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsFormsFormPublicModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsFormsFormPublicModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsFormsFormPublicModel} The populated <code>HelloAssoApiV5CommonModelsFormsFormPublicModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsFormsFormPublicModel();

            if (data.hasOwnProperty('organizationLogo')) {
                obj['organizationLogo'] = ApiClient.convertToType(data['organizationLogo'], 'String');
            }
            if (data.hasOwnProperty('organizationName')) {
                obj['organizationName'] = ApiClient.convertToType(data['organizationName'], 'String');
            }
            if (data.hasOwnProperty('tiers')) {
                obj['tiers'] = ApiClient.convertToType(data['tiers'], [HelloAssoApiV5CommonModelsFormsTierPublicModel]);
            }
            if (data.hasOwnProperty('activityType')) {
                obj['activityType'] = ApiClient.convertToType(data['activityType'], 'String');
            }
            if (data.hasOwnProperty('activityTypeId')) {
                obj['activityTypeId'] = ApiClient.convertToType(data['activityTypeId'], 'Number');
            }
            if (data.hasOwnProperty('place')) {
                obj['place'] = HelloAssoApiV5CommonModelsCommonPlaceModel.constructFromObject(data['place']);
            }
            if (data.hasOwnProperty('saleEndDate')) {
                obj['saleEndDate'] = ApiClient.convertToType(data['saleEndDate'], 'Date');
            }
            if (data.hasOwnProperty('saleStartDate')) {
                obj['saleStartDate'] = ApiClient.convertToType(data['saleStartDate'], 'Date');
            }
            if (data.hasOwnProperty('validityType')) {
                obj['validityType'] = HelloAssoApiV5CommonModelsEnumsMembershipValidityType.constructFromObject(data['validityType']);
            }
            if (data.hasOwnProperty('personalizedMessage')) {
                obj['personalizedMessage'] = ApiClient.convertToType(data['personalizedMessage'], 'String');
            }
            if (data.hasOwnProperty('banner')) {
                obj['banner'] = HelloAssoApiV5CommonModelsCommonDocumentModel.constructFromObject(data['banner']);
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = HelloAssoApiV5CommonModelsCommonDocumentModel.constructFromObject(data['logo']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = HelloAssoApiV5CommonModelsCommonMetaModel.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = HelloAssoApiV5CommonModelsEnumsFormState.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('privateTitle')) {
                obj['privateTitle'] = ApiClient.convertToType(data['privateTitle'], 'String');
            }
            if (data.hasOwnProperty('widgetButtonUrl')) {
                obj['widgetButtonUrl'] = ApiClient.convertToType(data['widgetButtonUrl'], 'String');
            }
            if (data.hasOwnProperty('widgetFullUrl')) {
                obj['widgetFullUrl'] = ApiClient.convertToType(data['widgetFullUrl'], 'String');
            }
            if (data.hasOwnProperty('widgetVignetteHorizontalUrl')) {
                obj['widgetVignetteHorizontalUrl'] = ApiClient.convertToType(data['widgetVignetteHorizontalUrl'], 'String');
            }
            if (data.hasOwnProperty('widgetVignetteVerticalUrl')) {
                obj['widgetVignetteVerticalUrl'] = ApiClient.convertToType(data['widgetVignetteVerticalUrl'], 'String');
            }
            if (data.hasOwnProperty('widgetCounterUrl')) {
                obj['widgetCounterUrl'] = ApiClient.convertToType(data['widgetCounterUrl'], 'String');
            }
            if (data.hasOwnProperty('formSlug')) {
                obj['formSlug'] = ApiClient.convertToType(data['formSlug'], 'String');
            }
            if (data.hasOwnProperty('formType')) {
                obj['formType'] = HelloAssoApiV5CommonModelsEnumsFormType.constructFromObject(data['formType']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('organizationSlug')) {
                obj['organizationSlug'] = ApiClient.convertToType(data['organizationSlug'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsFormsFormPublicModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsFormsFormPublicModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['organizationLogo'] && !(typeof data['organizationLogo'] === 'string' || data['organizationLogo'] instanceof String)) {
            throw new Error("Expected the field `organizationLogo` to be a primitive type in the JSON string but got " + data['organizationLogo']);
        }
        // ensure the json data is a string
        if (data['organizationName'] && !(typeof data['organizationName'] === 'string' || data['organizationName'] instanceof String)) {
            throw new Error("Expected the field `organizationName` to be a primitive type in the JSON string but got " + data['organizationName']);
        }
        if (data['tiers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tiers'])) {
                throw new Error("Expected the field `tiers` to be an array in the JSON data but got " + data['tiers']);
            }
            // validate the optional field `tiers` (array)
            for (const item of data['tiers']) {
                HelloAssoApiV5CommonModelsFormsTierPublicModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['activityType'] && !(typeof data['activityType'] === 'string' || data['activityType'] instanceof String)) {
            throw new Error("Expected the field `activityType` to be a primitive type in the JSON string but got " + data['activityType']);
        }
        // validate the optional field `place`
        if (data['place']) { // data not null
          HelloAssoApiV5CommonModelsCommonPlaceModel.validateJSON(data['place']);
        }
        // ensure the json data is a string
        if (data['personalizedMessage'] && !(typeof data['personalizedMessage'] === 'string' || data['personalizedMessage'] instanceof String)) {
            throw new Error("Expected the field `personalizedMessage` to be a primitive type in the JSON string but got " + data['personalizedMessage']);
        }
        // validate the optional field `banner`
        if (data['banner']) { // data not null
          HelloAssoApiV5CommonModelsCommonDocumentModel.validateJSON(data['banner']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `logo`
        if (data['logo']) { // data not null
          HelloAssoApiV5CommonModelsCommonDocumentModel.validateJSON(data['logo']);
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          HelloAssoApiV5CommonModelsCommonMetaModel.validateJSON(data['meta']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['privateTitle'] && !(typeof data['privateTitle'] === 'string' || data['privateTitle'] instanceof String)) {
            throw new Error("Expected the field `privateTitle` to be a primitive type in the JSON string but got " + data['privateTitle']);
        }
        // ensure the json data is a string
        if (data['widgetButtonUrl'] && !(typeof data['widgetButtonUrl'] === 'string' || data['widgetButtonUrl'] instanceof String)) {
            throw new Error("Expected the field `widgetButtonUrl` to be a primitive type in the JSON string but got " + data['widgetButtonUrl']);
        }
        // ensure the json data is a string
        if (data['widgetFullUrl'] && !(typeof data['widgetFullUrl'] === 'string' || data['widgetFullUrl'] instanceof String)) {
            throw new Error("Expected the field `widgetFullUrl` to be a primitive type in the JSON string but got " + data['widgetFullUrl']);
        }
        // ensure the json data is a string
        if (data['widgetVignetteHorizontalUrl'] && !(typeof data['widgetVignetteHorizontalUrl'] === 'string' || data['widgetVignetteHorizontalUrl'] instanceof String)) {
            throw new Error("Expected the field `widgetVignetteHorizontalUrl` to be a primitive type in the JSON string but got " + data['widgetVignetteHorizontalUrl']);
        }
        // ensure the json data is a string
        if (data['widgetVignetteVerticalUrl'] && !(typeof data['widgetVignetteVerticalUrl'] === 'string' || data['widgetVignetteVerticalUrl'] instanceof String)) {
            throw new Error("Expected the field `widgetVignetteVerticalUrl` to be a primitive type in the JSON string but got " + data['widgetVignetteVerticalUrl']);
        }
        // ensure the json data is a string
        if (data['widgetCounterUrl'] && !(typeof data['widgetCounterUrl'] === 'string' || data['widgetCounterUrl'] instanceof String)) {
            throw new Error("Expected the field `widgetCounterUrl` to be a primitive type in the JSON string but got " + data['widgetCounterUrl']);
        }
        // ensure the json data is a string
        if (data['formSlug'] && !(typeof data['formSlug'] === 'string' || data['formSlug'] instanceof String)) {
            throw new Error("Expected the field `formSlug` to be a primitive type in the JSON string but got " + data['formSlug']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['organizationSlug'] && !(typeof data['organizationSlug'] === 'string' || data['organizationSlug'] instanceof String)) {
            throw new Error("Expected the field `organizationSlug` to be a primitive type in the JSON string but got " + data['organizationSlug']);
        }

        return true;
    }


}



/**
 * Organization Logo
 * @member {String} organizationLogo
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['organizationLogo'] = undefined;

/**
 * Organization Name
 * @member {String} organizationName
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['organizationName'] = undefined;

/**
 * Tiers
 * @member {Array.<module:model/HelloAssoApiV5CommonModelsFormsTierPublicModel>} tiers
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['tiers'] = undefined;

/**
 * Activity type of the event eg. \"Atelier(s) / Stage(s)\" matching one of the provided type values <a href=\"index#!/Values/Values_Get\"> provided here</a> or a custom value is allowed.
 * @member {String} activityType
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['activityType'] = undefined;

/**
 * Activity type identifier
 * @member {Number} activityTypeId
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['activityTypeId'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsCommonPlaceModel} place
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['place'] = undefined;

/**
 * The datetime (Inclusive) at which the sales end.  If null the orders will be available until the end of the campaign.
 * @member {Date} saleEndDate
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['saleEndDate'] = undefined;

/**
 * The datetime (Inclusive) at which the users can start placing orders.  If null the orders will be available as soon as the campaign is published.
 * @member {Date} saleStartDate
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['saleStartDate'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsEnumsMembershipValidityType} validityType
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['validityType'] = undefined;

/**
 * A message customized by the organization administrator.
 * @member {String} personalizedMessage
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['personalizedMessage'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsCommonDocumentModel} banner
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['banner'] = undefined;

/**
 * Currency
 * @member {String} currency
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['currency'] = undefined;

/**
 * Short description (one line)
 * @member {String} description
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['description'] = undefined;

/**
 * The datetime of the activity start
 * @member {Date} startDate
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['startDate'] = undefined;

/**
 * The datetime of the activity end
 * @member {Date} endDate
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['endDate'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsCommonDocumentModel} logo
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['logo'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsCommonMetaModel} meta
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['meta'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsEnumsFormState} state
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['state'] = undefined;

/**
 * Title
 * @member {String} title
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['title'] = undefined;

/**
 * Private Title
 * @member {String} privateTitle
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['privateTitle'] = undefined;

/**
 * Url of the widget button
 * @member {String} widgetButtonUrl
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['widgetButtonUrl'] = undefined;

/**
 * Url of the form widget
 * @member {String} widgetFullUrl
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['widgetFullUrl'] = undefined;

/**
 * Url of the horizontal vignette widget
 * @member {String} widgetVignetteHorizontalUrl
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['widgetVignetteHorizontalUrl'] = undefined;

/**
 * Url of the vertical vignette widget
 * @member {String} widgetVignetteVerticalUrl
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['widgetVignetteVerticalUrl'] = undefined;

/**
 * Url of the counter widget
 * @member {String} widgetCounterUrl
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['widgetCounterUrl'] = undefined;

/**
 * The form slug
 * @member {String} formSlug
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['formSlug'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsEnumsFormType} formType
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['formType'] = undefined;

/**
 * The form url
 * @member {String} url
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['url'] = undefined;

/**
 * The organization slug
 * @member {String} organizationSlug
 */
HelloAssoApiV5CommonModelsFormsFormPublicModel.prototype['organizationSlug'] = undefined;






export default HelloAssoApiV5CommonModelsFormsFormPublicModel;

