/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5CommonModelsEnumsSortField.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5CommonModelsEnumsSortField {
    
        /**
         * value: "Date"
         * @const
         */
        "Date" = "Date";

    
        /**
         * value: "UpdateDate"
         * @const
         */
        "UpdateDate" = "UpdateDate";

    
        /**
         * value: "CreationDate"
         * @const
         */
        "CreationDate" = "CreationDate";

    

    /**
    * Returns a <code>HelloAssoApiV5CommonModelsEnumsSortField</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5CommonModelsEnumsSortField} The enum <code>HelloAssoApiV5CommonModelsEnumsSortField</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

