/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5CommonModelsEnumsFormState from './HelloAssoApiV5CommonModelsEnumsFormState';

/**
 * The HelloAssoApiV5CommonModelsFormsFormStateRequest model module.
 * @module model/HelloAssoApiV5CommonModelsFormsFormStateRequest
 * @version public
 */
class HelloAssoApiV5CommonModelsFormsFormStateRequest {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsFormsFormStateRequest</code>.
     * Update the from state
     * @alias module:model/HelloAssoApiV5CommonModelsFormsFormStateRequest
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsFormsFormStateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsFormsFormStateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsFormsFormStateRequest} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsFormsFormStateRequest} The populated <code>HelloAssoApiV5CommonModelsFormsFormStateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsFormsFormStateRequest();

            if (data.hasOwnProperty('state')) {
                obj['state'] = HelloAssoApiV5CommonModelsEnumsFormState.constructFromObject(data['state']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsFormsFormStateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsFormsFormStateRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/HelloAssoApiV5CommonModelsEnumsFormState} state
 */
HelloAssoApiV5CommonModelsFormsFormStateRequest.prototype['state'] = undefined;






export default HelloAssoApiV5CommonModelsFormsFormStateRequest;

