/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5CommonModelsStatisticsFormDisplayType.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5CommonModelsStatisticsFormDisplayType {
    
        /**
         * value: "CrowdFunding"
         * @const
         */
        "CrowdFunding" = "CrowdFunding";

    
        /**
         * value: "Membership"
         * @const
         */
        "Membership" = "Membership";

    
        /**
         * value: "Event"
         * @const
         */
        "Event" = "Event";

    
        /**
         * value: "Donation"
         * @const
         */
        "Donation" = "Donation";

    
        /**
         * value: "PaymentForm"
         * @const
         */
        "PaymentForm" = "PaymentForm";

    
        /**
         * value: "Checkout"
         * @const
         */
        "Checkout" = "Checkout";

    
        /**
         * value: "Shop"
         * @const
         */
        "Shop" = "Shop";

    
        /**
         * value: "Other"
         * @const
         */
        "Other" = "Other";

    
        /**
         * value: "Sale"
         * @const
         */
        "Sale" = "Sale";

    

    /**
    * Returns a <code>HelloAssoApiV5CommonModelsStatisticsFormDisplayType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5CommonModelsStatisticsFormDisplayType} The enum <code>HelloAssoApiV5CommonModelsStatisticsFormDisplayType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

