/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption model module.
 * @module model/HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption
 * @version public
 */
class HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption {
    /**
     * Constructs a new <code>HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption</code>.
     * @alias module:model/HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption
     */
    constructor() { 
        
        HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption} obj Optional instance to populate.
     * @return {module:model/HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption} The populated <code>HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'String');
            }
            if (data.hasOwnProperty('root')) {
                obj['root'] = ApiClient.convertToType(data['root'], 'String');
            }
            if (data.hasOwnProperty('separator')) {
                obj['separator'] = ApiClient.convertToType(data['separator'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['order'] && !(typeof data['order'] === 'string' || data['order'] instanceof String)) {
            throw new Error("Expected the field `order` to be a primitive type in the JSON string but got " + data['order']);
        }
        // ensure the json data is a string
        if (data['root'] && !(typeof data['root'] === 'string' || data['root'] instanceof String)) {
            throw new Error("Expected the field `root` to be a primitive type in the JSON string but got " + data['root']);
        }
        // ensure the json data is a string
        if (data['separator'] && !(typeof data['separator'] === 'string' || data['separator'] instanceof String)) {
            throw new Error("Expected the field `separator` to be a primitive type in the JSON string but got " + data['separator']);
        }

        return true;
    }


}



/**
 * @member {String} date
 */
HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption.prototype['date'] = undefined;

/**
 * @member {String} order
 */
HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption.prototype['order'] = undefined;

/**
 * @member {String} root
 */
HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption.prototype['root'] = undefined;

/**
 * @member {String} separator
 */
HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption.prototype['separator'] = undefined;






export default HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption;

