/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5CommonModelsEnumsItemState.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5CommonModelsEnumsItemState {
    
        /**
         * value: "Waiting"
         * @const
         */
        "Waiting" = "Waiting";

    
        /**
         * value: "Processed"
         * @const
         */
        "Processed" = "Processed";

    
        /**
         * value: "Registered"
         * @const
         */
        "Registered" = "Registered";

    
        /**
         * value: "Deleted"
         * @const
         */
        "Deleted" = "Deleted";

    
        /**
         * value: "Unknown"
         * @const
         */
        "Unknown" = "Unknown";

    
        /**
         * value: "Canceled"
         * @const
         */
        "Canceled" = "Canceled";

    
        /**
         * value: "Refused"
         * @const
         */
        "Refused" = "Refused";

    
        /**
         * value: "Abandoned"
         * @const
         */
        "Abandoned" = "Abandoned";

    

    /**
    * Returns a <code>HelloAssoApiV5CommonModelsEnumsItemState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5CommonModelsEnumsItemState} The enum <code>HelloAssoApiV5CommonModelsEnumsItemState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

