/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType {
    
        /**
         * value: "Payment"
         * @const
         */
        "Payment" = "Payment";

    
        /**
         * value: "Order"
         * @const
         */
        "Order" = "Order";

    
        /**
         * value: "Form"
         * @const
         */
        "Form" = "Form";

    
        /**
         * value: "Organization"
         * @const
         */
        "Organization" = "Organization";

    

    /**
    * Returns a <code>HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType} The enum <code>HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

