/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5ModelsEnumsPaymentMeans.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5ModelsEnumsPaymentMeans {
    
        /**
         * value: "None"
         * @const
         */
        "None" = "None";

    
        /**
         * value: "Card"
         * @const
         */
        "Card" = "Card";

    
        /**
         * value: "Sepa"
         * @const
         */
        "Sepa" = "Sepa";

    
        /**
         * value: "Check"
         * @const
         */
        "Check" = "Check";

    
        /**
         * value: "Cash"
         * @const
         */
        "Cash" = "Cash";

    
        /**
         * value: "BankTransfer"
         * @const
         */
        "BankTransfer" = "BankTransfer";

    
        /**
         * value: "Other"
         * @const
         */
        "Other" = "Other";

    

    /**
    * Returns a <code>HelloAssoApiV5ModelsEnumsPaymentMeans</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5ModelsEnumsPaymentMeans} The enum <code>HelloAssoApiV5ModelsEnumsPaymentMeans</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

