/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5CommonModelsEnumsPaymentCashOutState.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5CommonModelsEnumsPaymentCashOutState {
    
        /**
         * value: "MoneyIn"
         * @const
         */
        "MoneyIn" = "MoneyIn";

    
        /**
         * value: "CantTransferReceiverFull"
         * @const
         */
        "CantTransferReceiverFull" = "CantTransferReceiverFull";

    
        /**
         * value: "Transfered"
         * @const
         */
        "Transfered" = "Transfered";

    
        /**
         * value: "Refunded"
         * @const
         */
        "Refunded" = "Refunded";

    
        /**
         * value: "Refunding"
         * @const
         */
        "Refunding" = "Refunding";

    
        /**
         * value: "WaitingForCashOutConfirmation"
         * @const
         */
        "WaitingForCashOutConfirmation" = "WaitingForCashOutConfirmation";

    
        /**
         * value: "CashedOut"
         * @const
         */
        "CashedOut" = "CashedOut";

    
        /**
         * value: "Unknown"
         * @const
         */
        "Unknown" = "Unknown";

    
        /**
         * value: "Contested"
         * @const
         */
        "Contested" = "Contested";

    
        /**
         * value: "TransferInProgress"
         * @const
         */
        "TransferInProgress" = "TransferInProgress";

    

    /**
    * Returns a <code>HelloAssoApiV5CommonModelsEnumsPaymentCashOutState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5CommonModelsEnumsPaymentCashOutState} The enum <code>HelloAssoApiV5CommonModelsEnumsPaymentCashOutState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

