/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5ModelsCommonMetaModel from './HelloAssoApiV5ModelsCommonMetaModel';
import HelloAssoApiV5ModelsEnumsPaymentCashOutState from './HelloAssoApiV5ModelsEnumsPaymentCashOutState';
import HelloAssoApiV5ModelsEnumsPaymentMeans from './HelloAssoApiV5ModelsEnumsPaymentMeans';
import HelloAssoApiV5ModelsEnumsPaymentState from './HelloAssoApiV5ModelsEnumsPaymentState';
import HelloAssoApiV5ModelsEnumsPaymentType from './HelloAssoApiV5ModelsEnumsPaymentType';
import HelloAssoApiV5ModelsStatisticsRefundOperationLightModel from './HelloAssoApiV5ModelsStatisticsRefundOperationLightModel';

/**
 * The HelloAssoApiV5ModelsStatisticsItemPayment model module.
 * @module model/HelloAssoApiV5ModelsStatisticsItemPayment
 * @version public
 */
class HelloAssoApiV5ModelsStatisticsItemPayment {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsStatisticsItemPayment</code>.
     * Payment linked to the item
     * @alias module:model/HelloAssoApiV5ModelsStatisticsItemPayment
     */
    constructor() { 
        
        HelloAssoApiV5ModelsStatisticsItemPayment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsStatisticsItemPayment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsStatisticsItemPayment} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsStatisticsItemPayment} The populated <code>HelloAssoApiV5ModelsStatisticsItemPayment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsStatisticsItemPayment();

            if (data.hasOwnProperty('cashOutState')) {
                obj['cashOutState'] = HelloAssoApiV5ModelsEnumsPaymentCashOutState.constructFromObject(data['cashOutState']);
            }
            if (data.hasOwnProperty('shareAmount')) {
                obj['shareAmount'] = ApiClient.convertToType(data['shareAmount'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('amountTip')) {
                obj['amountTip'] = ApiClient.convertToType(data['amountTip'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('paymentMeans')) {
                obj['paymentMeans'] = HelloAssoApiV5ModelsEnumsPaymentMeans.constructFromObject(data['paymentMeans']);
            }
            if (data.hasOwnProperty('installmentNumber')) {
                obj['installmentNumber'] = ApiClient.convertToType(data['installmentNumber'], 'Number');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = HelloAssoApiV5ModelsEnumsPaymentState.constructFromObject(data['state']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = HelloAssoApiV5ModelsEnumsPaymentType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = HelloAssoApiV5ModelsCommonMetaModel.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('paymentOffLineMean')) {
                obj['paymentOffLineMean'] = HelloAssoApiV5ModelsEnumsPaymentMeans.constructFromObject(data['paymentOffLineMean']);
            }
            if (data.hasOwnProperty('refundOperations')) {
                obj['refundOperations'] = ApiClient.convertToType(data['refundOperations'], [HelloAssoApiV5ModelsStatisticsRefundOperationLightModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsStatisticsItemPayment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsStatisticsItemPayment</code>.
     */
    static validateJSON(data) {
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          HelloAssoApiV5ModelsCommonMetaModel.validateJSON(data['meta']);
        }
        if (data['refundOperations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['refundOperations'])) {
                throw new Error("Expected the field `refundOperations` to be an array in the JSON data but got " + data['refundOperations']);
            }
            // validate the optional field `refundOperations` (array)
            for (const item of data['refundOperations']) {
                HelloAssoApiV5ModelsStatisticsRefundOperationLightModel.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/HelloAssoApiV5ModelsEnumsPaymentCashOutState} cashOutState
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['cashOutState'] = undefined;

/**
 * Amount of the item and extra options payed on this payment term (in cents)
 * @member {Number} shareAmount
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['shareAmount'] = undefined;

/**
 * The ID of the payment
 * @member {Number} id
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['id'] = undefined;

/**
 * Total Amount of the payment (in cents)
 * @member {Number} amount
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['amount'] = undefined;

/**
 * Tip Amount of the payment (in cents)
 * @member {Number} amountTip
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['amountTip'] = undefined;

/**
 * Date of the payment
 * @member {Date} date
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['date'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5ModelsEnumsPaymentMeans} paymentMeans
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['paymentMeans'] = undefined;

/**
 * Indicates the payment number (useful in the case of an order comprising payments with installments)
 * @member {Number} installmentNumber
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['installmentNumber'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5ModelsEnumsPaymentState} state
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['state'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5ModelsEnumsPaymentType} type
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['type'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5ModelsCommonMetaModel} meta
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['meta'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5ModelsEnumsPaymentMeans} paymentOffLineMean
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['paymentOffLineMean'] = undefined;

/**
 * The refund operations information for the specific payment.
 * @member {Array.<module:model/HelloAssoApiV5ModelsStatisticsRefundOperationLightModel>} refundOperations
 */
HelloAssoApiV5ModelsStatisticsItemPayment.prototype['refundOperations'] = undefined;






export default HelloAssoApiV5ModelsStatisticsItemPayment;

