/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5CommonModelsCommonImageModel from './HelloAssoApiV5CommonModelsCommonImageModel';
import HelloAssoApiV5CommonModelsCommonVideoModel from './HelloAssoApiV5CommonModelsCommonVideoModel';
import HelloAssoApiV5CommonModelsEnumsOrganizationType from './HelloAssoApiV5CommonModelsEnumsOrganizationType';
import HelloAssoModelsEnumsGlobalRole from './HelloAssoModelsEnumsGlobalRole';
import HelloAssoModelsSharedGeoLocation from './HelloAssoModelsSharedGeoLocation';

/**
 * The HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel model module.
 * @module model/HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel
 * @version public
 */
class HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel</code>.
     * @alias module:model/HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel} The populated <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel();

            if (data.hasOwnProperty('facebookPage')) {
                obj['facebookPage'] = ApiClient.convertToType(data['facebookPage'], 'String');
            }
            if (data.hasOwnProperty('galleryImages')) {
                obj['galleryImages'] = ApiClient.convertToType(data['galleryImages'], [HelloAssoApiV5CommonModelsCommonImageModel]);
            }
            if (data.hasOwnProperty('longDescription')) {
                obj['longDescription'] = ApiClient.convertToType(data['longDescription'], 'String');
            }
            if (data.hasOwnProperty('twitterPage')) {
                obj['twitterPage'] = ApiClient.convertToType(data['twitterPage'], 'String');
            }
            if (data.hasOwnProperty('videos')) {
                obj['videos'] = ApiClient.convertToType(data['videos'], [HelloAssoApiV5CommonModelsCommonVideoModel]);
            }
            if (data.hasOwnProperty('webSite')) {
                obj['webSite'] = ApiClient.convertToType(data['webSite'], 'String');
            }
            if (data.hasOwnProperty('isAuthenticated')) {
                obj['isAuthenticated'] = ApiClient.convertToType(data['isAuthenticated'], 'Boolean');
            }
            if (data.hasOwnProperty('isCashInCompliant')) {
                obj['isCashInCompliant'] = ApiClient.convertToType(data['isCashInCompliant'], 'Boolean');
            }
            if (data.hasOwnProperty('banner')) {
                obj['banner'] = ApiClient.convertToType(data['banner'], 'String');
            }
            if (data.hasOwnProperty('fiscalReceiptEligibility')) {
                obj['fiscalReceiptEligibility'] = ApiClient.convertToType(data['fiscalReceiptEligibility'], 'Boolean');
            }
            if (data.hasOwnProperty('fiscalReceiptIssuanceEnabled')) {
                obj['fiscalReceiptIssuanceEnabled'] = ApiClient.convertToType(data['fiscalReceiptIssuanceEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = HelloAssoApiV5CommonModelsEnumsOrganizationType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('geolocation')) {
                obj['geolocation'] = HelloAssoModelsSharedGeoLocation.constructFromObject(data['geolocation']);
            }
            if (data.hasOwnProperty('rnaNumber')) {
                obj['rnaNumber'] = ApiClient.convertToType(data['rnaNumber'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = HelloAssoModelsEnumsGlobalRole.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('zipCode')) {
                obj['zipCode'] = ApiClient.convertToType(data['zipCode'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('updateDate')) {
                obj['updateDate'] = ApiClient.convertToType(data['updateDate'], 'Date');
            }
            if (data.hasOwnProperty('categoryJoId')) {
                obj['categoryJoId'] = ApiClient.convertToType(data['categoryJoId'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('organizationSlug')) {
                obj['organizationSlug'] = ApiClient.convertToType(data['organizationSlug'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['facebookPage'] && !(typeof data['facebookPage'] === 'string' || data['facebookPage'] instanceof String)) {
            throw new Error("Expected the field `facebookPage` to be a primitive type in the JSON string but got " + data['facebookPage']);
        }
        if (data['galleryImages']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['galleryImages'])) {
                throw new Error("Expected the field `galleryImages` to be an array in the JSON data but got " + data['galleryImages']);
            }
            // validate the optional field `galleryImages` (array)
            for (const item of data['galleryImages']) {
                HelloAssoApiV5CommonModelsCommonImageModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['longDescription'] && !(typeof data['longDescription'] === 'string' || data['longDescription'] instanceof String)) {
            throw new Error("Expected the field `longDescription` to be a primitive type in the JSON string but got " + data['longDescription']);
        }
        // ensure the json data is a string
        if (data['twitterPage'] && !(typeof data['twitterPage'] === 'string' || data['twitterPage'] instanceof String)) {
            throw new Error("Expected the field `twitterPage` to be a primitive type in the JSON string but got " + data['twitterPage']);
        }
        if (data['videos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['videos'])) {
                throw new Error("Expected the field `videos` to be an array in the JSON data but got " + data['videos']);
            }
            // validate the optional field `videos` (array)
            for (const item of data['videos']) {
                HelloAssoApiV5CommonModelsCommonVideoModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['webSite'] && !(typeof data['webSite'] === 'string' || data['webSite'] instanceof String)) {
            throw new Error("Expected the field `webSite` to be a primitive type in the JSON string but got " + data['webSite']);
        }
        // ensure the json data is a string
        if (data['banner'] && !(typeof data['banner'] === 'string' || data['banner'] instanceof String)) {
            throw new Error("Expected the field `banner` to be a primitive type in the JSON string but got " + data['banner']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // validate the optional field `geolocation`
        if (data['geolocation']) { // data not null
          HelloAssoModelsSharedGeoLocation.validateJSON(data['geolocation']);
        }
        // ensure the json data is a string
        if (data['rnaNumber'] && !(typeof data['rnaNumber'] === 'string' || data['rnaNumber'] instanceof String)) {
            throw new Error("Expected the field `rnaNumber` to be a primitive type in the JSON string but got " + data['rnaNumber']);
        }
        // ensure the json data is a string
        if (data['logo'] && !(typeof data['logo'] === 'string' || data['logo'] instanceof String)) {
            throw new Error("Expected the field `logo` to be a primitive type in the JSON string but got " + data['logo']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['zipCode'] && !(typeof data['zipCode'] === 'string' || data['zipCode'] instanceof String)) {
            throw new Error("Expected the field `zipCode` to be a primitive type in the JSON string but got " + data['zipCode']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['organizationSlug'] && !(typeof data['organizationSlug'] === 'string' || data['organizationSlug'] instanceof String)) {
            throw new Error("Expected the field `organizationSlug` to be a primitive type in the JSON string but got " + data['organizationSlug']);
        }

        return true;
    }


}



/**
 * @member {String} facebookPage
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['facebookPage'] = undefined;

/**
 * @member {Array.<module:model/HelloAssoApiV5CommonModelsCommonImageModel>} galleryImages
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['galleryImages'] = undefined;

/**
 * @member {String} longDescription
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['longDescription'] = undefined;

/**
 * @member {String} twitterPage
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['twitterPage'] = undefined;

/**
 * @member {Array.<module:model/HelloAssoApiV5CommonModelsCommonVideoModel>} videos
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['videos'] = undefined;

/**
 * @member {String} webSite
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['webSite'] = undefined;

/**
 * The organization is authenticated. Property returned only when asked by an organization admin.
 * @member {Boolean} isAuthenticated
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['isAuthenticated'] = undefined;

/**
 * If transaction can be init on the organization or not. Property returned only when asked by an organization admin.
 * @member {Boolean} isCashInCompliant
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['isCashInCompliant'] = undefined;

/**
 * The organization banner
 * @member {String} banner
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['banner'] = undefined;

/**
 * The organism can issue fiscal receipts (type ok and has not deactivated it)  Must configure it and be authenticated to become enabled
 * @member {Boolean} fiscalReceiptEligibility
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['fiscalReceiptEligibility'] = undefined;

/**
 * The organism is eligible, has set up his options, and is authenticated.
 * @member {Boolean} fiscalReceiptIssuanceEnabled
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['fiscalReceiptIssuanceEnabled'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsEnumsOrganizationType} type
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['type'] = undefined;

/**
 * Organization category label
 * @member {String} category
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['category'] = undefined;

/**
 * Organization Address (for authorized applications or if authorized by the organization)
 * @member {String} address
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['address'] = undefined;

/**
 * @member {module:model/HelloAssoModelsSharedGeoLocation} geolocation
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['geolocation'] = undefined;

/**
 * Unique identifier assigned when creating the association
 * @member {String} rnaNumber
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['rnaNumber'] = undefined;

/**
 * Logo of organization
 * @member {String} logo
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['logo'] = undefined;

/**
 * Name of organization
 * @member {String} name
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['name'] = undefined;

/**
 * @member {module:model/HelloAssoModelsEnumsGlobalRole} role
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['role'] = undefined;

/**
 * Organization city
 * @member {String} city
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['city'] = undefined;

/**
 * Organization zip code
 * @member {String} zipCode
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['zipCode'] = undefined;

/**
 * Organization description
 * @member {String} description
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['description'] = undefined;

/**
 * Last update date of the organization
 * @member {Date} updateDate
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['updateDate'] = undefined;

/**
 * @member {Number} categoryJoId
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['categoryJoId'] = undefined;

/**
 * The organization url
 * @member {String} url
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['url'] = undefined;

/**
 * The organization slug
 * @member {String} organizationSlug
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel.prototype['organizationSlug'] = undefined;






export default HelloAssoApiV5CommonModelsOrganizationsOrganizationPublicModel;

