/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel from './HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel';

/**
 * The HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel model module.
 * @module model/HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel
 * @version public
 */
class HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel</code>.
     * ExtraOptionFullModel
     * @alias module:model/HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel} The populated <code>HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel();

            if (data.hasOwnProperty('customFields')) {
                obj['customFields'] = ApiClient.convertToType(data['customFields'], [HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('vatRate')) {
                obj['vatRate'] = ApiClient.convertToType(data['vatRate'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('isRequired')) {
                obj['isRequired'] = ApiClient.convertToType(data['isRequired'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel</code>.
     */
    static validateJSON(data) {
        if (data['customFields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customFields'])) {
                throw new Error("Expected the field `customFields` to be an array in the JSON data but got " + data['customFields']);
            }
            // validate the optional field `customFields` (array)
            for (const item of data['customFields']) {
                HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * List of custom fields to be filled by the user
 * @member {Array.<module:model/HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel>} customFields
 */
HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.prototype['customFields'] = undefined;

/**
 * Id
 * @member {Number} id
 */
HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.prototype['id'] = undefined;

/**
 * Price of the extraOption, can be free
 * @member {Number} price
 */
HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.prototype['price'] = undefined;

/**
 * Vat rate if applicable  Amount have to be 0.10 for 10%
 * @member {Number} vatRate
 */
HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.prototype['vatRate'] = undefined;

/**
 * The name of the option
 * @member {String} label
 */
HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.prototype['label'] = undefined;

/**
 * The description of the option
 * @member {String} description
 */
HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.prototype['description'] = undefined;

/**
 * Additional option is required/mandatory
 * @member {Boolean} isRequired
 */
HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.prototype['isRequired'] = undefined;






export default HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel;

