/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoApiV5ModelsCartsCheckoutTerm model module.
 * @module model/HelloAssoApiV5ModelsCartsCheckoutTerm
 * @version public
 */
class HelloAssoApiV5ModelsCartsCheckoutTerm {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsCartsCheckoutTerm</code>.
     * @alias module:model/HelloAssoApiV5ModelsCartsCheckoutTerm
     * @param amount {Number} Term amount, all taxes included, in cents
     * @param date {Date} Term date
     */
    constructor(amount, date) { 
        
        HelloAssoApiV5ModelsCartsCheckoutTerm.initialize(this, amount, date);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, date) { 
        obj['amount'] = amount;
        obj['date'] = date;
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsCartsCheckoutTerm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsCartsCheckoutTerm} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsCartsCheckoutTerm} The populated <code>HelloAssoApiV5ModelsCartsCheckoutTerm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsCartsCheckoutTerm();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsCartsCheckoutTerm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsCartsCheckoutTerm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HelloAssoApiV5ModelsCartsCheckoutTerm.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

HelloAssoApiV5ModelsCartsCheckoutTerm.RequiredProperties = ["amount", "date"];

/**
 * Term amount, all taxes included, in cents
 * @member {Number} amount
 */
HelloAssoApiV5ModelsCartsCheckoutTerm.prototype['amount'] = undefined;

/**
 * Term date
 * @member {Date} date
 */
HelloAssoApiV5ModelsCartsCheckoutTerm.prototype['date'] = undefined;






export default HelloAssoApiV5ModelsCartsCheckoutTerm;

