/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel model module.
 * @module model/HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel
 * @version public
 */
class HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel {
    /**
     * Constructs a new <code>HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel</code>.
     * @alias module:model/HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel
     */
    constructor() { 
        
        HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel} The populated <code>HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('function')) {
                obj['function'] = ApiClient.convertToType(data['function'], 'String');
            }
            if (data.hasOwnProperty('fileUrl')) {
                obj['fileUrl'] = ApiClient.convertToType(data['fileUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['function'] && !(typeof data['function'] === 'string' || data['function'] instanceof String)) {
            throw new Error("Expected the field `function` to be a primitive type in the JSON string but got " + data['function']);
        }
        // ensure the json data is a string
        if (data['fileUrl'] && !(typeof data['fileUrl'] === 'string' || data['fileUrl'] instanceof String)) {
            throw new Error("Expected the field `fileUrl` to be a primitive type in the JSON string but got " + data['fileUrl']);
        }

        return true;
    }


}



/**
 * @member {String} firstName
 */
HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel.prototype['lastName'] = undefined;

/**
 * @member {String} function
 */
HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel.prototype['function'] = undefined;

/**
 * @member {String} fileUrl
 */
HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel.prototype['fileUrl'] = undefined;






export default HelloAssoModelsAccountsOrganizationLegalInformationsFiscalReceiptSignatoryModel;

