/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoApiV5CommonModelsFormsFormQuickCreateModel model module.
 * @module model/HelloAssoApiV5CommonModelsFormsFormQuickCreateModel
 * @version public
 */
class HelloAssoApiV5CommonModelsFormsFormQuickCreateModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsFormsFormQuickCreateModel</code>.
     * @alias module:model/HelloAssoApiV5CommonModelsFormsFormQuickCreateModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsFormsFormQuickCreateModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsFormsFormQuickCreateModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsFormsFormQuickCreateModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsFormsFormQuickCreateModel} The populated <code>HelloAssoApiV5CommonModelsFormsFormQuickCreateModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsFormsFormQuickCreateModel();

            if (data.hasOwnProperty('formSlug')) {
                obj['formSlug'] = ApiClient.convertToType(data['formSlug'], 'String');
            }
            if (data.hasOwnProperty('organizationSlug')) {
                obj['organizationSlug'] = ApiClient.convertToType(data['organizationSlug'], 'String');
            }
            if (data.hasOwnProperty('publicUrl')) {
                obj['publicUrl'] = ApiClient.convertToType(data['publicUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsFormsFormQuickCreateModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsFormsFormQuickCreateModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['formSlug'] && !(typeof data['formSlug'] === 'string' || data['formSlug'] instanceof String)) {
            throw new Error("Expected the field `formSlug` to be a primitive type in the JSON string but got " + data['formSlug']);
        }
        // ensure the json data is a string
        if (data['organizationSlug'] && !(typeof data['organizationSlug'] === 'string' || data['organizationSlug'] instanceof String)) {
            throw new Error("Expected the field `organizationSlug` to be a primitive type in the JSON string but got " + data['organizationSlug']);
        }
        // ensure the json data is a string
        if (data['publicUrl'] && !(typeof data['publicUrl'] === 'string' || data['publicUrl'] instanceof String)) {
            throw new Error("Expected the field `publicUrl` to be a primitive type in the JSON string but got " + data['publicUrl']);
        }

        return true;
    }


}



/**
 * @member {String} formSlug
 */
HelloAssoApiV5CommonModelsFormsFormQuickCreateModel.prototype['formSlug'] = undefined;

/**
 * @member {String} organizationSlug
 */
HelloAssoApiV5CommonModelsFormsFormQuickCreateModel.prototype['organizationSlug'] = undefined;

/**
 * @member {String} publicUrl
 */
HelloAssoApiV5CommonModelsFormsFormQuickCreateModel.prototype['publicUrl'] = undefined;






export default HelloAssoApiV5CommonModelsFormsFormQuickCreateModel;

