/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoApiV5CommonModelsCommonVideoModel model module.
 * @module model/HelloAssoApiV5CommonModelsCommonVideoModel
 * @version public
 */
class HelloAssoApiV5CommonModelsCommonVideoModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsCommonVideoModel</code>.
     * @alias module:model/HelloAssoApiV5CommonModelsCommonVideoModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsCommonVideoModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsCommonVideoModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsCommonVideoModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsCommonVideoModel} The populated <code>HelloAssoApiV5CommonModelsCommonVideoModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsCommonVideoModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsCommonVideoModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsCommonVideoModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
HelloAssoApiV5CommonModelsCommonVideoModel.prototype['id'] = undefined;

/**
 * @member {String} url
 */
HelloAssoApiV5CommonModelsCommonVideoModel.prototype['url'] = undefined;






export default HelloAssoApiV5CommonModelsCommonVideoModel;

