/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5CommonModelsEnumsFormType from './HelloAssoApiV5CommonModelsEnumsFormType';

/**
 * The HelloAssoApiV5CommonModelsFormsFormBasicModel model module.
 * @module model/HelloAssoApiV5CommonModelsFormsFormBasicModel
 * @version public
 */
class HelloAssoApiV5CommonModelsFormsFormBasicModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsFormsFormBasicModel</code>.
     * A basic form model
     * @alias module:model/HelloAssoApiV5CommonModelsFormsFormBasicModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsFormsFormBasicModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsFormsFormBasicModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsFormsFormBasicModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsFormsFormBasicModel} The populated <code>HelloAssoApiV5CommonModelsFormsFormBasicModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsFormsFormBasicModel();

            if (data.hasOwnProperty('formSlug')) {
                obj['formSlug'] = ApiClient.convertToType(data['formSlug'], 'String');
            }
            if (data.hasOwnProperty('formType')) {
                obj['formType'] = HelloAssoApiV5CommonModelsEnumsFormType.constructFromObject(data['formType']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('organizationSlug')) {
                obj['organizationSlug'] = ApiClient.convertToType(data['organizationSlug'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsFormsFormBasicModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsFormsFormBasicModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['formSlug'] && !(typeof data['formSlug'] === 'string' || data['formSlug'] instanceof String)) {
            throw new Error("Expected the field `formSlug` to be a primitive type in the JSON string but got " + data['formSlug']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['organizationSlug'] && !(typeof data['organizationSlug'] === 'string' || data['organizationSlug'] instanceof String)) {
            throw new Error("Expected the field `organizationSlug` to be a primitive type in the JSON string but got " + data['organizationSlug']);
        }

        return true;
    }


}



/**
 * The form slug
 * @member {String} formSlug
 */
HelloAssoApiV5CommonModelsFormsFormBasicModel.prototype['formSlug'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsEnumsFormType} formType
 */
HelloAssoApiV5CommonModelsFormsFormBasicModel.prototype['formType'] = undefined;

/**
 * The form url
 * @member {String} url
 */
HelloAssoApiV5CommonModelsFormsFormBasicModel.prototype['url'] = undefined;

/**
 * The organization slug
 * @member {String} organizationSlug
 */
HelloAssoApiV5CommonModelsFormsFormBasicModel.prototype['organizationSlug'] = undefined;






export default HelloAssoApiV5CommonModelsFormsFormBasicModel;

