/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5CommonModelsStatisticsFormDisplayType from './HelloAssoApiV5CommonModelsStatisticsFormDisplayType';

/**
 * The HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData model module.
 * @module model/HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData
 * @version public
 */
class HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData</code>.
     * @alias module:model/HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData} The populated <code>HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData();

            if (data.hasOwnProperty('formDisplayType')) {
                obj['formDisplayType'] = HelloAssoApiV5CommonModelsStatisticsFormDisplayType.constructFromObject(data['formDisplayType']);
            }
            if (data.hasOwnProperty('isTapToPay')) {
                obj['isTapToPay'] = ApiClient.convertToType(data['isTapToPay'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/HelloAssoApiV5CommonModelsStatisticsFormDisplayType} formDisplayType
 */
HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData.prototype['formDisplayType'] = undefined;

/**
 * Whether or not the payment was made using tap to pay.
 * @member {Boolean} isTapToPay
 */
HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData.prototype['isTapToPay'] = undefined;






export default HelloAssoApiV5CommonModelsStatisticsPaymentDisplayData;

