/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoApiV5ModelsCommonMetaModel model module.
 * @module model/HelloAssoApiV5ModelsCommonMetaModel
 * @version public
 */
class HelloAssoApiV5ModelsCommonMetaModel {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsCommonMetaModel</code>.
     * MetaModel class
     * @alias module:model/HelloAssoApiV5ModelsCommonMetaModel
     */
    constructor() { 
        
        HelloAssoApiV5ModelsCommonMetaModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsCommonMetaModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsCommonMetaModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsCommonMetaModel} The populated <code>HelloAssoApiV5ModelsCommonMetaModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsCommonMetaModel();

            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsCommonMetaModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsCommonMetaModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * CreatedAt
 * @member {Date} createdAt
 */
HelloAssoApiV5ModelsCommonMetaModel.prototype['createdAt'] = undefined;

/**
 * UpdateAt
 * @member {Date} updatedAt
 */
HelloAssoApiV5ModelsCommonMetaModel.prototype['updatedAt'] = undefined;






export default HelloAssoApiV5ModelsCommonMetaModel;

