/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5ModelsEnumsPriceCategory from './HelloAssoApiV5ModelsEnumsPriceCategory';
import HelloAssoApiV5ModelsStatisticsItemCustomField from './HelloAssoApiV5ModelsStatisticsItemCustomField';

/**
 * The HelloAssoApiV5ModelsStatisticsItemOption model module.
 * @module model/HelloAssoApiV5ModelsStatisticsItemOption
 * @version public
 */
class HelloAssoApiV5ModelsStatisticsItemOption {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsStatisticsItemOption</code>.
     * ItemOption class
     * @alias module:model/HelloAssoApiV5ModelsStatisticsItemOption
     */
    constructor() { 
        
        HelloAssoApiV5ModelsStatisticsItemOption.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsStatisticsItemOption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsStatisticsItemOption} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsStatisticsItemOption} The populated <code>HelloAssoApiV5ModelsStatisticsItemOption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsStatisticsItemOption();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('priceCategory')) {
                obj['priceCategory'] = HelloAssoApiV5ModelsEnumsPriceCategory.constructFromObject(data['priceCategory']);
            }
            if (data.hasOwnProperty('isRequired')) {
                obj['isRequired'] = ApiClient.convertToType(data['isRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('customFields')) {
                obj['customFields'] = ApiClient.convertToType(data['customFields'], [HelloAssoApiV5ModelsStatisticsItemCustomField]);
            }
            if (data.hasOwnProperty('optionId')) {
                obj['optionId'] = ApiClient.convertToType(data['optionId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsStatisticsItemOption</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsStatisticsItemOption</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['customFields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customFields'])) {
                throw new Error("Expected the field `customFields` to be an array in the JSON data but got " + data['customFields']);
            }
            // validate the optional field `customFields` (array)
            for (const item of data['customFields']) {
                HelloAssoApiV5ModelsStatisticsItemCustomField.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Name of the option
 * @member {String} name
 */
HelloAssoApiV5ModelsStatisticsItemOption.prototype['name'] = undefined;

/**
 * Amount of the option in cents
 * @member {Number} amount
 */
HelloAssoApiV5ModelsStatisticsItemOption.prototype['amount'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5ModelsEnumsPriceCategory} priceCategory
 */
HelloAssoApiV5ModelsStatisticsItemOption.prototype['priceCategory'] = undefined;

/**
 * Option is required or optional
 * @member {Boolean} isRequired
 */
HelloAssoApiV5ModelsStatisticsItemOption.prototype['isRequired'] = undefined;

/**
 * Custom fields related to this option
 * @member {Array.<module:model/HelloAssoApiV5ModelsStatisticsItemCustomField>} customFields
 */
HelloAssoApiV5ModelsStatisticsItemOption.prototype['customFields'] = undefined;

/**
 * @member {Number} optionId
 */
HelloAssoApiV5ModelsStatisticsItemOption.prototype['optionId'] = undefined;






export default HelloAssoApiV5ModelsStatisticsItemOption;

