/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5ModelsEnumsFieldType from './HelloAssoApiV5ModelsEnumsFieldType';

/**
 * The HelloAssoApiV5ModelsFormsCustomFieldPublicModel model module.
 * @module model/HelloAssoApiV5ModelsFormsCustomFieldPublicModel
 * @version public
 */
class HelloAssoApiV5ModelsFormsCustomFieldPublicModel {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsFormsCustomFieldPublicModel</code>.
     * A custom field can be assigned to a Tier or an ExtraOption  It is used to give extra information during the reservation of a tier
     * @alias module:model/HelloAssoApiV5ModelsFormsCustomFieldPublicModel
     */
    constructor() { 
        
        HelloAssoApiV5ModelsFormsCustomFieldPublicModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsFormsCustomFieldPublicModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsFormsCustomFieldPublicModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsFormsCustomFieldPublicModel} The populated <code>HelloAssoApiV5ModelsFormsCustomFieldPublicModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsFormsCustomFieldPublicModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], ['String']);
            }
            if (data.hasOwnProperty('isRequired')) {
                obj['isRequired'] = ApiClient.convertToType(data['isRequired'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = HelloAssoApiV5ModelsEnumsFieldType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsFormsCustomFieldPublicModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsFormsCustomFieldPublicModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['values'])) {
            throw new Error("Expected the field `values` to be an array in the JSON data but got " + data['values']);
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }

        return true;
    }


}



/**
 * Id of the customField
 * @member {Number} id
 */
HelloAssoApiV5ModelsFormsCustomFieldPublicModel.prototype['id'] = undefined;

/**
 * The list of possible values if type is a CHOICE_LIST
 * @member {Array.<String>} values
 */
HelloAssoApiV5ModelsFormsCustomFieldPublicModel.prototype['values'] = undefined;

/**
 * True if the custom field must be filled by the user before validating a cart
 * @member {Boolean} isRequired
 */
HelloAssoApiV5ModelsFormsCustomFieldPublicModel.prototype['isRequired'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5ModelsEnumsFieldType} type
 */
HelloAssoApiV5ModelsFormsCustomFieldPublicModel.prototype['type'] = undefined;

/**
 * The label to be displayed to the user
 * @member {String} label
 */
HelloAssoApiV5ModelsFormsCustomFieldPublicModel.prototype['label'] = undefined;






export default HelloAssoApiV5ModelsFormsCustomFieldPublicModel;

