/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5CommonModelsCommonDocumentModel from './HelloAssoApiV5CommonModelsCommonDocumentModel';
import HelloAssoApiV5CommonModelsCommonMetaModel from './HelloAssoApiV5CommonModelsCommonMetaModel';
import HelloAssoApiV5CommonModelsEnumsPaymentFrequencyType from './HelloAssoApiV5CommonModelsEnumsPaymentFrequencyType';
import HelloAssoApiV5CommonModelsEnumsTierType from './HelloAssoApiV5CommonModelsEnumsTierType';
import HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel from './HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel';
import HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel from './HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel';
import HelloAssoApiV5CommonModelsFormsTermModel from './HelloAssoApiV5CommonModelsFormsTermModel';

/**
 * The HelloAssoApiV5CommonModelsFormsTierPublicModel model module.
 * @module model/HelloAssoApiV5CommonModelsFormsTierPublicModel
 * @version public
 */
class HelloAssoApiV5CommonModelsFormsTierPublicModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsFormsTierPublicModel</code>.
     * TierPublicModel class
     * @alias module:model/HelloAssoApiV5CommonModelsFormsTierPublicModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsFormsTierPublicModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsFormsTierPublicModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsFormsTierPublicModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsFormsTierPublicModel} The populated <code>HelloAssoApiV5CommonModelsFormsTierPublicModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsFormsTierPublicModel();

            if (data.hasOwnProperty('customFields')) {
                obj['customFields'] = ApiClient.convertToType(data['customFields'], [HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel]);
            }
            if (data.hasOwnProperty('extraOptions')) {
                obj['extraOptions'] = ApiClient.convertToType(data['extraOptions'], [HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('tierType')) {
                obj['tierType'] = HelloAssoApiV5CommonModelsEnumsTierType.constructFromObject(data['tierType']);
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('vatRate')) {
                obj['vatRate'] = ApiClient.convertToType(data['vatRate'], 'Number');
            }
            if (data.hasOwnProperty('minAmount')) {
                obj['minAmount'] = ApiClient.convertToType(data['minAmount'], 'Number');
            }
            if (data.hasOwnProperty('paymentFrequency')) {
                obj['paymentFrequency'] = HelloAssoApiV5CommonModelsEnumsPaymentFrequencyType.constructFromObject(data['paymentFrequency']);
            }
            if (data.hasOwnProperty('maxPerUser')) {
                obj['maxPerUser'] = ApiClient.convertToType(data['maxPerUser'], 'Number');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = HelloAssoApiV5CommonModelsCommonMetaModel.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('saleStartDate')) {
                obj['saleStartDate'] = ApiClient.convertToType(data['saleStartDate'], 'Date');
            }
            if (data.hasOwnProperty('saleEndDate')) {
                obj['saleEndDate'] = ApiClient.convertToType(data['saleEndDate'], 'Date');
            }
            if (data.hasOwnProperty('isEligibleTaxReceipt')) {
                obj['isEligibleTaxReceipt'] = ApiClient.convertToType(data['isEligibleTaxReceipt'], 'Boolean');
            }
            if (data.hasOwnProperty('terms')) {
                obj['terms'] = ApiClient.convertToType(data['terms'], [HelloAssoApiV5CommonModelsFormsTermModel]);
            }
            if (data.hasOwnProperty('picture')) {
                obj['picture'] = HelloAssoApiV5CommonModelsCommonDocumentModel.constructFromObject(data['picture']);
            }
            if (data.hasOwnProperty('isExcludedFromFormPaymentTerms')) {
                obj['isExcludedFromFormPaymentTerms'] = ApiClient.convertToType(data['isExcludedFromFormPaymentTerms'], 'Boolean');
            }
            if (data.hasOwnProperty('isFavorite')) {
                obj['isFavorite'] = ApiClient.convertToType(data['isFavorite'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsFormsTierPublicModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsFormsTierPublicModel</code>.
     */
    static validateJSON(data) {
        if (data['customFields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customFields'])) {
                throw new Error("Expected the field `customFields` to be an array in the JSON data but got " + data['customFields']);
            }
            // validate the optional field `customFields` (array)
            for (const item of data['customFields']) {
                HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel.validateJSON(item);
            };
        }
        if (data['extraOptions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['extraOptions'])) {
                throw new Error("Expected the field `extraOptions` to be an array in the JSON data but got " + data['extraOptions']);
            }
            // validate the optional field `extraOptions` (array)
            for (const item of data['extraOptions']) {
                HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          HelloAssoApiV5CommonModelsCommonMetaModel.validateJSON(data['meta']);
        }
        if (data['terms']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['terms'])) {
                throw new Error("Expected the field `terms` to be an array in the JSON data but got " + data['terms']);
            }
            // validate the optional field `terms` (array)
            for (const item of data['terms']) {
                HelloAssoApiV5CommonModelsFormsTermModel.validateJSON(item);
            };
        }
        // validate the optional field `picture`
        if (data['picture']) { // data not null
          HelloAssoApiV5CommonModelsCommonDocumentModel.validateJSON(data['picture']);
        }

        return true;
    }


}



/**
 * List of custom fields to be filled by the user
 * @member {Array.<module:model/HelloAssoApiV5CommonModelsFormsCustomFieldPublicModel>} customFields
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['customFields'] = undefined;

/**
 * List of available extra options to buy along the tier
 * @member {Array.<module:model/HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel>} extraOptions
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['extraOptions'] = undefined;

/**
 * id
 * @member {Number} id
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['id'] = undefined;

/**
 * label
 * @member {String} label
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['label'] = undefined;

/**
 * description
 * @member {String} description
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['description'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsEnumsTierType} tierType
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['tierType'] = undefined;

/**
 * the Price in cents  if price equals 0 then it is free or there is a MinAmount
 * @member {Number} price
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['price'] = undefined;

/**
 * Vat rate if applicable  Amount have to be 0.10 for 10%
 * @member {Number} vatRate
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['vatRate'] = undefined;

/**
 * If set, it means the payment is free to choose, according to the specified minAmount in cents
 * @member {Number} minAmount
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['minAmount'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsEnumsPaymentFrequencyType} paymentFrequency
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['paymentFrequency'] = undefined;

/**
 * Max quantity buyable in this cart
 * @member {Number} maxPerUser
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['maxPerUser'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsCommonMetaModel} meta
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['meta'] = undefined;

/**
 * The datetime (Inclusive) at which the users can start buying this tier.  If null the tier will be available at the start of the event.
 * @member {Date} saleStartDate
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['saleStartDate'] = undefined;

/**
 * The datetime (Inclusive) at which the tier is no longer available.  If null the tier will be available until the end of the event.
 * @member {Date} saleEndDate
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['saleEndDate'] = undefined;

/**
 * Whether this is eligible to a deduction
 * @member {Boolean} isEligibleTaxReceipt
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['isEligibleTaxReceipt'] = undefined;

/**
 * Terms of tier
 * @member {Array.<module:model/HelloAssoApiV5CommonModelsFormsTermModel>} terms
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['terms'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsCommonDocumentModel} picture
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['picture'] = undefined;

/**
 * True means this tier must be paid in the initial payment, false means it can be paid in payment with installments  Null when the form payment terms are disabled or not compatible with the related form
 * @member {Boolean} isExcludedFromFormPaymentTerms
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['isExcludedFromFormPaymentTerms'] = undefined;

/**
 * Indicates whether this tier is marked as a favorite.  Used only in Donation form type.
 * @member {Boolean} isFavorite
 */
HelloAssoApiV5CommonModelsFormsTierPublicModel.prototype['isFavorite'] = undefined;






export default HelloAssoApiV5CommonModelsFormsTierPublicModel;

