/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5CommonModelsEnumsSortOrder.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5CommonModelsEnumsSortOrder {
    
        /**
         * value: "Asc"
         * @const
         */
        "Asc" = "Asc";

    
        /**
         * value: "Desc"
         * @const
         */
        "Desc" = "Desc";

    

    /**
    * Returns a <code>HelloAssoApiV5CommonModelsEnumsSortOrder</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5CommonModelsEnumsSortOrder} The enum <code>HelloAssoApiV5CommonModelsEnumsSortOrder</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

