/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus {
    
        /**
         * value: "Paid"
         * @const
         */
        "Paid" = "Paid";

    
        /**
         * value: "Refunded"
         * @const
         */
        "Refunded" = "Refunded";

    
        /**
         * value: "PartiallyRefunded"
         * @const
         */
        "PartiallyRefunded" = "PartiallyRefunded";

    
        /**
         * value: "Contested"
         * @const
         */
        "Contested" = "Contested";

    

    /**
    * Returns a <code>HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus} The enum <code>HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

