/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HelloAssoApiV5ModelsEnumsMembershipValidityType.
* @enum {}
* @readonly
*/
export default class HelloAssoApiV5ModelsEnumsMembershipValidityType {
    
        /**
         * value: "MovingYear"
         * @const
         */
        "MovingYear" = "MovingYear";

    
        /**
         * value: "Custom"
         * @const
         */
        "Custom" = "Custom";

    
        /**
         * value: "Illimited"
         * @const
         */
        "Illimited" = "Illimited";

    

    /**
    * Returns a <code>HelloAssoApiV5ModelsEnumsMembershipValidityType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HelloAssoApiV5ModelsEnumsMembershipValidityType} The enum <code>HelloAssoApiV5ModelsEnumsMembershipValidityType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

