/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoApiV5ModelsFormsTermModel model module.
 * @module model/HelloAssoApiV5ModelsFormsTermModel
 * @version public
 */
class HelloAssoApiV5ModelsFormsTermModel {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsFormsTermModel</code>.
     * TermsModel class
     * @alias module:model/HelloAssoApiV5ModelsFormsTermModel
     */
    constructor() { 
        
        HelloAssoApiV5ModelsFormsTermModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsFormsTermModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsFormsTermModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsFormsTermModel} The populated <code>HelloAssoApiV5ModelsFormsTermModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsFormsTermModel();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsFormsTermModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsFormsTermModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Term Date
 * @member {Date} date
 */
HelloAssoApiV5ModelsFormsTermModel.prototype['date'] = undefined;

/**
 * Term Amount
 * @member {Number} amount
 */
HelloAssoApiV5ModelsFormsTermModel.prototype['amount'] = undefined;






export default HelloAssoApiV5ModelsFormsTermModel;

