/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5ModelsEnumsFieldType from './HelloAssoApiV5ModelsEnumsFieldType';

/**
 * The HelloAssoApiV5ModelsStatisticsItemCustomField model module.
 * @module model/HelloAssoApiV5ModelsStatisticsItemCustomField
 * @version public
 */
class HelloAssoApiV5ModelsStatisticsItemCustomField {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsStatisticsItemCustomField</code>.
     * Custom field associated with the item or option
     * @alias module:model/HelloAssoApiV5ModelsStatisticsItemCustomField
     */
    constructor() { 
        
        HelloAssoApiV5ModelsStatisticsItemCustomField.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsStatisticsItemCustomField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsStatisticsItemCustomField} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsStatisticsItemCustomField} The populated <code>HelloAssoApiV5ModelsStatisticsItemCustomField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsStatisticsItemCustomField();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = HelloAssoApiV5ModelsEnumsFieldType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('answer')) {
                obj['answer'] = ApiClient.convertToType(data['answer'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsStatisticsItemCustomField</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsStatisticsItemCustomField</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['answer'] && !(typeof data['answer'] === 'string' || data['answer'] instanceof String)) {
            throw new Error("Expected the field `answer` to be a primitive type in the JSON string but got " + data['answer']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
HelloAssoApiV5ModelsStatisticsItemCustomField.prototype['id'] = undefined;

/**
 * @member {String} name
 */
HelloAssoApiV5ModelsStatisticsItemCustomField.prototype['name'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5ModelsEnumsFieldType} type
 */
HelloAssoApiV5ModelsStatisticsItemCustomField.prototype['type'] = undefined;

/**
 * Participant or user answer
 * @member {String} answer
 */
HelloAssoApiV5ModelsStatisticsItemCustomField.prototype['answer'] = undefined;






export default HelloAssoApiV5ModelsStatisticsItemCustomField;

