/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoApiV5ModelsStatisticsOrderAmountModel model module.
 * @module model/HelloAssoApiV5ModelsStatisticsOrderAmountModel
 * @version public
 */
class HelloAssoApiV5ModelsStatisticsOrderAmountModel {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsStatisticsOrderAmountModel</code>.
     * @alias module:model/HelloAssoApiV5ModelsStatisticsOrderAmountModel
     */
    constructor() { 
        
        HelloAssoApiV5ModelsStatisticsOrderAmountModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsStatisticsOrderAmountModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsStatisticsOrderAmountModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsStatisticsOrderAmountModel} The populated <code>HelloAssoApiV5ModelsStatisticsOrderAmountModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsStatisticsOrderAmountModel();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('vat')) {
                obj['vat'] = ApiClient.convertToType(data['vat'], 'Number');
            }
            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsStatisticsOrderAmountModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsStatisticsOrderAmountModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Total amount in cents
 * @member {Number} total
 */
HelloAssoApiV5ModelsStatisticsOrderAmountModel.prototype['total'] = undefined;

/**
 * Vat amount in cents
 * @member {Number} vat
 */
HelloAssoApiV5ModelsStatisticsOrderAmountModel.prototype['vat'] = undefined;

/**
 * Discount amount in cents
 * @member {Number} discount
 */
HelloAssoApiV5ModelsStatisticsOrderAmountModel.prototype['discount'] = undefined;






export default HelloAssoApiV5ModelsStatisticsOrderAmountModel;

