/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel model module.
 * @module model/HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel
 * @version public
 */
class HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel</code>.
     * A basic organization model
     * @alias module:model/HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel} The populated <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('organizationSlug')) {
                obj['organizationSlug'] = ApiClient.convertToType(data['organizationSlug'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['organizationSlug'] && !(typeof data['organizationSlug'] === 'string' || data['organizationSlug'] instanceof String)) {
            throw new Error("Expected the field `organizationSlug` to be a primitive type in the JSON string but got " + data['organizationSlug']);
        }

        return true;
    }


}



/**
 * The organization url
 * @member {String} url
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel.prototype['url'] = undefined;

/**
 * The organization slug
 * @member {String} organizationSlug
 */
HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel.prototype['organizationSlug'] = undefined;






export default HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel;

