/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType from './HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType';

/**
 * The HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel model module.
 * @module model/HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel
 * @version public
 */
class HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel {
    /**
     * Constructs a new <code>HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel</code>.
     * Organization notification URL Model class
     * @alias module:model/HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel
     */
    constructor() { 
        
        HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel} The populated <code>HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('apiNotificationType')) {
                obj['apiNotificationType'] = HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType.constructFromObject(data['apiNotificationType']);
            }
            if (data.hasOwnProperty('signatureKey')) {
                obj['signatureKey'] = ApiClient.convertToType(data['signatureKey'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['signatureKey'] && !(typeof data['signatureKey'] === 'string' || data['signatureKey'] instanceof String)) {
            throw new Error("Expected the field `signatureKey` to be a primitive type in the JSON string but got " + data['signatureKey']);
        }

        return true;
    }


}



/**
 * The notification Url
 * @member {String} url
 */
HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel.prototype['url'] = undefined;

/**
 * @member {module:model/HelloAssoApiV5CommonModelsApiNotificationsApiNotificationType} apiNotificationType
 */
HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel.prototype['apiNotificationType'] = undefined;

/**
 * Signature Key : allows you to verify the authenticity of notifications
 * @member {String} signatureKey
 */
HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel.prototype['signatureKey'] = undefined;






export default HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel;

