/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloAssoApiV5ModelsStatisticsPayer model module.
 * @module model/HelloAssoApiV5ModelsStatisticsPayer
 * @version public
 */
class HelloAssoApiV5ModelsStatisticsPayer {
    /**
     * Constructs a new <code>HelloAssoApiV5ModelsStatisticsPayer</code>.
     * @alias module:model/HelloAssoApiV5ModelsStatisticsPayer
     */
    constructor() { 
        
        HelloAssoApiV5ModelsStatisticsPayer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelloAssoApiV5ModelsStatisticsPayer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloAssoApiV5ModelsStatisticsPayer} obj Optional instance to populate.
     * @return {module:model/HelloAssoApiV5ModelsStatisticsPayer} The populated <code>HelloAssoApiV5ModelsStatisticsPayer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloAssoApiV5ModelsStatisticsPayer();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('zipCode')) {
                obj['zipCode'] = ApiClient.convertToType(data['zipCode'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'Date');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloAssoApiV5ModelsStatisticsPayer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloAssoApiV5ModelsStatisticsPayer</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['zipCode'] && !(typeof data['zipCode'] === 'string' || data['zipCode'] instanceof String)) {
            throw new Error("Expected the field `zipCode` to be a primitive type in the JSON string but got " + data['zipCode']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['company'] && !(typeof data['company'] === 'string' || data['company'] instanceof String)) {
            throw new Error("Expected the field `company` to be a primitive type in the JSON string but got " + data['company']);
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }

        return true;
    }


}



/**
 * @member {String} email
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['email'] = undefined;

/**
 * Gets or Sets Address
 * @member {String} address
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['address'] = undefined;

/**
 * Gets or Sets City
 * @member {String} city
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['city'] = undefined;

/**
 * Gets or Sets ZipCode
 * @member {String} zipCode
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['zipCode'] = undefined;

/**
 * Gets or Sets Country
 * @member {String} country
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['country'] = undefined;

/**
 * Gets or Sets Company
 * @member {String} company
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['company'] = undefined;

/**
 * Gets or Sets date of birth
 * @member {Date} dateOfBirth
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['dateOfBirth'] = undefined;

/**
 * @member {String} firstName
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
HelloAssoApiV5ModelsStatisticsPayer.prototype['lastName'] = undefined;






export default HelloAssoApiV5ModelsStatisticsPayer;

