/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HelloAssoApiV5CommonModelsEnumsFormType from '../model/HelloAssoApiV5CommonModelsEnumsFormType';
import HelloAssoApiV5CommonModelsFormsFormStateRequest from '../model/HelloAssoApiV5CommonModelsFormsFormStateRequest';

/**
* Forms service.
* @module api/FormsApi
* @version public
*/
export default class FormsApi {

    /**
    * Constructs a new FormsApi. 
    * @alias module:api/FormsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the organizationsOrganizationSlugFormsFormTypeFormSlugStatePut operation.
     * @callback module:api/FormsApi~organizationsOrganizationSlugFormsFormTypeFormSlugStatePutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a form state
     * Update form state.<br/><br/><b>Your token must have one of these roles : </b><br/>FormAdmin<br/>OrganizationAdmin<br/><br/>If you are an <b>association</b>, you can obtain these roles with your client.<br/>If you are a <b>partner</b>, you can obtain these roles by the authorize flow.<br/><br/><b>Your clientId must be allowed all of those privileges : </b> <br/> FormAdministration<br/><br/>
     * @param {String} organizationSlug 
     * @param {String} formSlug 
     * @param {module:model/HelloAssoApiV5CommonModelsEnumsFormType} formType 
     * @param {Object} opts Optional parameters
     * @param {module:model/HelloAssoApiV5CommonModelsFormsFormStateRequest} [helloAssoApiV5CommonModelsFormsFormStateRequest] 
     * @param {module:api/FormsApi~organizationsOrganizationSlugFormsFormTypeFormSlugStatePutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    organizationsOrganizationSlugFormsFormTypeFormSlugStatePut(organizationSlug, formSlug, formType, opts, callback) {
      opts = opts || {};
      let postBody = opts['helloAssoApiV5CommonModelsFormsFormStateRequest'];
      // verify the required parameter 'organizationSlug' is set
      if (organizationSlug === undefined || organizationSlug === null) {
        throw new Error("Missing the required parameter 'organizationSlug' when calling organizationsOrganizationSlugFormsFormTypeFormSlugStatePut");
      }
      // verify the required parameter 'formSlug' is set
      if (formSlug === undefined || formSlug === null) {
        throw new Error("Missing the required parameter 'formSlug' when calling organizationsOrganizationSlugFormsFormTypeFormSlugStatePut");
      }
      // verify the required parameter 'formType' is set
      if (formType === undefined || formType === null) {
        throw new Error("Missing the required parameter 'formType' when calling organizationsOrganizationSlugFormsFormTypeFormSlugStatePut");
      }

      let pathParams = {
        'organizationSlug': organizationSlug,
        'formSlug': formSlug,
        'formType': formType
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/organizations/{organizationSlug}/forms/{formType}/{formSlug}/state', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
