/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel from '../model/HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel';
import HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest from '../model/HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest';

/**
* OrganizationPublicConfigurations service.
* @module api/OrganizationPublicConfigurationsApi
* @version public
*/
export default class OrganizationPublicConfigurationsApi {

    /**
    * Constructs a new OrganizationPublicConfigurationsApi. 
    * @alias module:api/OrganizationPublicConfigurationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the organizationsOrganizationSlugConfigurationsGet operation.
     * @callback module:api/OrganizationPublicConfigurationsApi~organizationsOrganizationSlugConfigurationsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * <br/><br/><b>Your token must have one of these roles : </b><br/>OrganizationAdmin<br/><br/>If you are an <b>association</b>, you can obtain these roles with your client.<br/>If you are a <b>partner</b>, you can obtain these roles by the authorize flow.<br/><br/><b>Your clientId must be allowed all of those privileges : </b> <br/> OrganizationAdministration<br/><br/>
     * @param {String} organizationSlug 
     * @param {module:api/OrganizationPublicConfigurationsApi~organizationsOrganizationSlugConfigurationsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel>}
     */
    organizationsOrganizationSlugConfigurationsGet(organizationSlug, callback) {
      let postBody = null;
      // verify the required parameter 'organizationSlug' is set
      if (organizationSlug === undefined || organizationSlug === null) {
        throw new Error("Missing the required parameter 'organizationSlug' when calling organizationsOrganizationSlugConfigurationsGet");
      }

      let pathParams = {
        'organizationSlug': organizationSlug
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel];
      return this.apiClient.callApi(
        '/organizations/{organizationSlug}/configurations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the organizationsOrganizationSlugConfigurationsPut operation.
     * @callback module:api/OrganizationPublicConfigurationsApi~organizationsOrganizationSlugConfigurationsPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * <br/><br/><b>Your token must have one of these roles : </b><br/>OrganizationAdmin<br/><br/>If you are an <b>association</b>, you can obtain these roles with your client.<br/>If you are a <b>partner</b>, you can obtain these roles by the authorize flow.<br/><br/><b>Your clientId must be allowed all of those privileges : </b> <br/> OrganizationAdministration<br/><br/>
     * @param {String} organizationSlug 
     * @param {Object} opts Optional parameters
     * @param {module:model/HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest} [helloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest] 
     * @param {module:api/OrganizationPublicConfigurationsApi~organizationsOrganizationSlugConfigurationsPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    organizationsOrganizationSlugConfigurationsPut(organizationSlug, opts, callback) {
      opts = opts || {};
      let postBody = opts['helloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest'];
      // verify the required parameter 'organizationSlug' is set
      if (organizationSlug === undefined || organizationSlug === null) {
        throw new Error("Missing the required parameter 'organizationSlug' when calling organizationsOrganizationSlugConfigurationsPut");
      }

      let pathParams = {
        'organizationSlug': organizationSlug
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/organizations/{organizationSlug}/configurations', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
