/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HelloAssoApiV5ModelsTagsInternalTagModel from '../model/HelloAssoApiV5ModelsTagsInternalTagModel';

/**
* Tags service.
* @module api/TagsApi
* @version public
*/
export default class TagsApi {

    /**
    * Constructs a new TagsApi. 
    * @alias module:api/TagsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the tagsTagNameGet operation.
     * @callback module:api/TagsApi~tagsTagNameGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HelloAssoApiV5ModelsTagsInternalTagModel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtenir le détail d'un tag interne
     * <br/><br/><b>Votre clientId doit être autorisé à tous ces privilèges : </b> <br/> FormOpenDirectory<br/><br/>
     * @param {String} tagName 
     * @param {Object} opts Optional parameters
     * @param {Boolean} [withCount = false)] If true : Count of times Tag is used
     * @param {Boolean} [withAmount = false)] If true : Amount collected by all forms linked to this Tag
     * @param {module:api/TagsApi~tagsTagNameGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HelloAssoApiV5ModelsTagsInternalTagModel}
     */
    tagsTagNameGet(tagName, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'tagName' is set
      if (tagName === undefined || tagName === null) {
        throw new Error("Missing the required parameter 'tagName' when calling tagsTagNameGet");
      }

      let pathParams = {
        'tagName': tagName
      };
      let queryParams = {
        'withCount': opts['withCount'],
        'withAmount': opts['withAmount']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = HelloAssoApiV5ModelsTagsInternalTagModel;
      return this.apiClient.callApi(
        '/tags/{tagName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
