/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel from '../model/HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel';

/**
* Utilisateurs service.
* @module api/UtilisateursApi
* @version public
*/
export default class UtilisateursApi {

    /**
    * Constructs a new UtilisateursApi. 
    * @alias module:api/UtilisateursApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the usersMeOrganizationsGet operation.
     * @callback module:api/UtilisateursApi~usersMeOrganizationsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtenir mes organisations
     * Renvoie la liste des organisations où l'utilisateur connecté a des droits<br/><br/><b>Votre clientId doit être autorisé à tous ces privilèges : </b> <br/> AccessPublicData<br/><br/>
     * @param {module:api/UtilisateursApi~usersMeOrganizationsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel>}
     */
    usersMeOrganizationsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel];
      return this.apiClient.callApi(
        '/users/me/organizations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
