/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HelloAssoApiV5CommonModelsEnumsFormType from '../model/HelloAssoApiV5CommonModelsEnumsFormType';
import HelloAssoApiV5CommonModelsFormsFormActivityModel from '../model/HelloAssoApiV5CommonModelsFormsFormActivityModel';

/**
* ValuesDefinitions service.
* @module api/ValuesDefinitionsApi
* @version public
*/
export default class ValuesDefinitionsApi {

    /**
    * Constructs a new ValuesDefinitionsApi. 
    * @alias module:api/ValuesDefinitionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the valuesFormFormTypeTypesGet operation.
     * @callback module:api/ValuesDefinitionsApi~valuesFormFormTypeTypesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/HelloAssoApiV5CommonModelsFormsFormActivityModel>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all activity types for a form type
     * Use this in order to build your dropdown of form subtypes<br/><br/><b>Your clientId must be allowed all of those privileges : </b> <br/> FormAdministration<br/><br/>
     * @param {module:model/HelloAssoApiV5CommonModelsEnumsFormType} formType 
     * @param {module:api/ValuesDefinitionsApi~valuesFormFormTypeTypesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/HelloAssoApiV5CommonModelsFormsFormActivityModel>}
     */
    valuesFormFormTypeTypesGet(formType, callback) {
      let postBody = null;
      // verify the required parameter 'formType' is set
      if (formType === undefined || formType === null) {
        throw new Error("Missing the required parameter 'formType' when calling valuesFormFormTypeTypesGet");
      }

      let pathParams = {
        'formType': formType
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [HelloAssoApiV5CommonModelsFormsFormActivityModel];
      return this.apiClient.callApi(
        '/values/form/{formType}/types', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
