/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HelloAssoApi);
  }
}(this, function(expect, HelloAssoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel', function() {
    it('should create an instance of HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel', function() {
      // uncomment below and update the code to test HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be.a(HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel);
    });

    it('should have the property campaignType (base name: "campaignType")', function() {
      // uncomment below and update the code to test the property campaignType
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property campaignName (base name: "campaignName")', function() {
      // uncomment below and update the code to test the property campaignName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property operationType (base name: "operationType")', function() {
      // uncomment below and update the code to test the property operationType
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property credit (base name: "credit")', function() {
      // uncomment below and update the code to test the property credit
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property debit (base name: "debit")', function() {
      // uncomment below and update the code to test the property debit
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property orderId (base name: "orderId")', function() {
      // uncomment below and update the code to test the property orderId
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property paymentId (base name: "paymentId")', function() {
      // uncomment below and update the code to test the property paymentId
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property paymentDate (base name: "paymentDate")', function() {
      // uncomment below and update the code to test the property paymentDate
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethod (base name: "paymentMethod")', function() {
      // uncomment below and update the code to test the property paymentMethod
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property paymentStatus (base name: "paymentStatus")', function() {
      // uncomment below and update the code to test the property paymentStatus
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property cashOutDate (base name: "cashOutDate")', function() {
      // uncomment below and update the code to test the property cashOutDate
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property cashOutId (base name: "cashOutId")', function() {
      // uncomment below and update the code to test the property cashOutId
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property designation (base name: "designation")', function() {
      // uncomment below and update the code to test the property designation
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property payerCompany (base name: "payerCompany")', function() {
      // uncomment below and update the code to test the property payerCompany
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property payerLastName (base name: "payerLastName")', function() {
      // uncomment below and update the code to test the property payerLastName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property payerFirstName (base name: "payerFirstName")', function() {
      // uncomment below and update the code to test the property payerFirstName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property payerEmail (base name: "payerEmail")', function() {
      // uncomment below and update the code to test the property payerEmail
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

    it('should have the property payerSiren (base name: "payerSiren")', function() {
      // uncomment below and update the code to test the property payerSiren
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel();
      //expect(instance).to.be();
    });

  });

}));
