/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HelloAssoApi);
  }
}(this, function(expect, HelloAssoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HelloAssoApiV5CommonModelsPartnersPartnerPublicModel', function() {
    it('should create an instance of HelloAssoApiV5CommonModelsPartnersPartnerPublicModel', function() {
      // uncomment below and update the code to test HelloAssoApiV5CommonModelsPartnersPartnerPublicModel
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be.a(HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

    it('should have the property logo (base name: "logo")', function() {
      // uncomment below and update the code to test the property logo
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

    it('should have the property logoRectangle (base name: "logoRectangle")', function() {
      // uncomment below and update the code to test the property logoRectangle
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

    it('should have the property apiClient (base name: "apiClient")', function() {
      // uncomment below and update the code to test the property apiClient
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

    it('should have the property urlNotificationList (base name: "urlNotificationList")', function() {
      // uncomment below and update the code to test the property urlNotificationList
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

    it('should have the property partnerStatistics (base name: "partnerStatistics")', function() {
      // uncomment below and update the code to test the property partnerStatistics
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsPartnersPartnerPublicModel();
      //expect(instance).to.be();
    });

  });

}));
