/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HelloAssoApi);
  }
}(this, function(expect, HelloAssoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HelloAssoApiV5CommonModelsDirectoryListFormsRequest', function() {
    it('should create an instance of HelloAssoApiV5CommonModelsDirectoryListFormsRequest', function() {
      // uncomment below and update the code to test HelloAssoApiV5CommonModelsDirectoryListFormsRequest
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be.a(HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest);
    });

    it('should have the property formName (base name: "formName")', function() {
      // uncomment below and update the code to test the property formName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formDescription (base name: "formDescription")', function() {
      // uncomment below and update the code to test the property formDescription
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formZipCodes (base name: "formZipCodes")', function() {
      // uncomment below and update the code to test the property formZipCodes
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formCities (base name: "formCities")', function() {
      // uncomment below and update the code to test the property formCities
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formRegions (base name: "formRegions")', function() {
      // uncomment below and update the code to test the property formRegions
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formDepartments (base name: "formDepartments")', function() {
      // uncomment below and update the code to test the property formDepartments
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formCountries (base name: "formCountries")', function() {
      // uncomment below and update the code to test the property formCountries
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formTypes (base name: "formTypes")', function() {
      // uncomment below and update the code to test the property formTypes
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formActivityType (base name: "formActivityType")', function() {
      // uncomment below and update the code to test the property formActivityType
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formPublicationStartDateMin (base name: "formPublicationStartDateMin")', function() {
      // uncomment below and update the code to test the property formPublicationStartDateMin
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formPublicationStartDateMax (base name: "formPublicationStartDateMax")', function() {
      // uncomment below and update the code to test the property formPublicationStartDateMax
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formStartDateMin (base name: "formStartDateMin")', function() {
      // uncomment below and update the code to test the property formStartDateMin
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formStartDateMax (base name: "formStartDateMax")', function() {
      // uncomment below and update the code to test the property formStartDateMax
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formEndDateMax (base name: "formEndDateMax")', function() {
      // uncomment below and update the code to test the property formEndDateMax
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formEndDateMin (base name: "formEndDateMin")', function() {
      // uncomment below and update the code to test the property formEndDateMin
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formIsFree (base name: "formIsFree")', function() {
      // uncomment below and update the code to test the property formIsFree
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formHasRemainingEntries (base name: "formHasRemainingEntries")', function() {
      // uncomment below and update the code to test the property formHasRemainingEntries
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formInternalTags (base name: "formInternalTags")', function() {
      // uncomment below and update the code to test the property formInternalTags
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property formPublicTags (base name: "formPublicTags")', function() {
      // uncomment below and update the code to test the property formPublicTags
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationName (base name: "organizationName")', function() {
      // uncomment below and update the code to test the property organizationName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationDescription (base name: "organizationDescription")', function() {
      // uncomment below and update the code to test the property organizationDescription
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationCategories (base name: "organizationCategories")', function() {
      // uncomment below and update the code to test the property organizationCategories
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationTypes (base name: "organizationTypes")', function() {
      // uncomment below and update the code to test the property organizationTypes
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationZipCodes (base name: "organizationZipCodes")', function() {
      // uncomment below and update the code to test the property organizationZipCodes
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationCities (base name: "organizationCities")', function() {
      // uncomment below and update the code to test the property organizationCities
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationRegions (base name: "organizationRegions")', function() {
      // uncomment below and update the code to test the property organizationRegions
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationDepartments (base name: "organizationDepartments")', function() {
      // uncomment below and update the code to test the property organizationDepartments
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationFiscalReceiptEligibility (base name: "organizationFiscalReceiptEligibility")', function() {
      // uncomment below and update the code to test the property organizationFiscalReceiptEligibility
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizationLinkedPartners (base name: "organizationLinkedPartners")', function() {
      // uncomment below and update the code to test the property organizationLinkedPartners
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsDirectoryListFormsRequest();
      //expect(instance).to.be();
    });

  });

}));
