/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HelloAssoApi);
  }
}(this, function(expect, HelloAssoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HelloAssoApiV5CommonModelsStatisticsPayer', function() {
    it('should create an instance of HelloAssoApiV5CommonModelsStatisticsPayer', function() {
      // uncomment below and update the code to test HelloAssoApiV5CommonModelsStatisticsPayer
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be.a(HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer);
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

    it('should have the property zipCode (base name: "zipCode")', function() {
      // uncomment below and update the code to test the property zipCode
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

    it('should have the property dateOfBirth (base name: "dateOfBirth")', function() {
      // uncomment below and update the code to test the property dateOfBirth
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsStatisticsPayer();
      //expect(instance).to.be();
    });

  });

}));
