/**
 * HelloAsso API
 * HelloAsso auto-generated SDK
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HelloAssoApi);
  }
}(this, function(expect, HelloAssoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest', function() {
    it('should create an instance of HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest', function() {
      // uncomment below and update the code to test HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be.a(HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest);
    });

    it('should have the property tierList (base name: "tierList")', function() {
      // uncomment below and update the code to test the property tierList
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property banner (base name: "banner")', function() {
      // uncomment below and update the code to test the property banner
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "endDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property logo (base name: "logo")', function() {
      // uncomment below and update the code to test the property logo
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property privateTitle (base name: "privateTitle")', function() {
      // uncomment below and update the code to test the property privateTitle
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "startDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property activityTypeId (base name: "activityTypeId")', function() {
      // uncomment below and update the code to test the property activityTypeId
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property place (base name: "place")', function() {
      // uncomment below and update the code to test the property place
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property saleEndDate (base name: "saleEndDate")', function() {
      // uncomment below and update the code to test the property saleEndDate
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property saleStartDate (base name: "saleStartDate")', function() {
      // uncomment below and update the code to test the property saleStartDate
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property validityType (base name: "validityType")', function() {
      // uncomment below and update the code to test the property validityType
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property acceptOpenDonation (base name: "acceptOpenDonation")', function() {
      // uncomment below and update the code to test the property acceptOpenDonation
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property acceptOpenMonthlyDonation (base name: "acceptOpenMonthlyDonation")', function() {
      // uncomment below and update the code to test the property acceptOpenMonthlyDonation
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowComment (base name: "allowComment")', function() {
      // uncomment below and update the code to test the property allowComment
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property amountVisible (base name: "amountVisible")', function() {
      // uncomment below and update the code to test the property amountVisible
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property widgetButtonText (base name: "widgetButtonText")', function() {
      // uncomment below and update the code to test the property widgetButtonText
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property contact (base name: "contact")', function() {
      // uncomment below and update the code to test the property contact
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property displayContributorName (base name: "displayContributorName")', function() {
      // uncomment below and update the code to test the property displayContributorName
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property displayParticipantsCount (base name: "displayParticipantsCount")', function() {
      // uncomment below and update the code to test the property displayParticipantsCount
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property displayRemainingEntries (base name: "displayRemainingEntries")', function() {
      // uncomment below and update the code to test the property displayRemainingEntries
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property financialGoal (base name: "financialGoal")', function() {
      // uncomment below and update the code to test the property financialGoal
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property generateMembershipCards (base name: "generateMembershipCards")', function() {
      // uncomment below and update the code to test the property generateMembershipCards
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property generateTickets (base name: "generateTickets")', function() {
      // uncomment below and update the code to test the property generateTickets
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property invertDescriptions (base name: "invertDescriptions")', function() {
      // uncomment below and update the code to test the property invertDescriptions
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property labelConditionsAndTermsFile (base name: "labelConditionsAndTermsFile")', function() {
      // uncomment below and update the code to test the property labelConditionsAndTermsFile
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property longDescription (base name: "longDescription")', function() {
      // uncomment below and update the code to test the property longDescription
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property openDonationPresetAmounts (base name: "openDonationPresetAmounts")', function() {
      // uncomment below and update the code to test the property openDonationPresetAmounts
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property personalizedMessage (base name: "personalizedMessage")', function() {
      // uncomment below and update the code to test the property personalizedMessage
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property projectBeneficiaries (base name: "projectBeneficiaries")', function() {
      // uncomment below and update the code to test the property projectBeneficiaries
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property projectExpensesDetails (base name: "projectExpensesDetails")', function() {
      // uncomment below and update the code to test the property projectExpensesDetails
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property projectOwners (base name: "projectOwners")', function() {
      // uncomment below and update the code to test the property projectOwners
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property suggestMonthlyDonation (base name: "suggestMonthlyDonation")', function() {
      // uncomment below and update the code to test the property suggestMonthlyDonation
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property displayMonthlyDonationsFirst (base name: "displayMonthlyDonationsFirst")', function() {
      // uncomment below and update the code to test the property displayMonthlyDonationsFirst
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property projectTargetCountry (base name: "projectTargetCountry")', function() {
      // uncomment below and update the code to test the property projectTargetCountry
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowOrganismPayer (base name: "allowOrganismPayer")', function() {
      // uncomment below and update the code to test the property allowOrganismPayer
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowIndividualPayer (base name: "allowIndividualPayer")', function() {
      // uncomment below and update the code to test the property allowIndividualPayer
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property displayVersion (base name: "displayVersion")', function() {
      // uncomment below and update the code to test the property displayVersion
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property remindAbandonedCart (base name: "remindAbandonedCart")', function() {
      // uncomment below and update the code to test the property remindAbandonedCart
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxEntries (base name: "maxEntries")', function() {
      // uncomment below and update the code to test the property maxEntries
      //var instance = new HelloAssoApi.HelloAssoApiV5CommonModelsFormsFormQuickCreateRequest();
      //expect(instance).to.be();
    });

  });

}));
