/**
 * HelloAsso API
 * HelloAsso Open Api specification
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HelloAssoApi);
  }
}(this, function(expect, HelloAssoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HelloAssoApi.CommandesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CommandesApi', function() {
    describe('itemsItemIdGet', function() {
      it('should call itemsItemIdGet successfully', function(done) {
        //uncomment below and update the code to test itemsItemIdGet
        //instance.itemsItemIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ordersOrderIdCancelPost', function() {
      it('should call ordersOrderIdCancelPost successfully', function(done) {
        //uncomment below and update the code to test ordersOrderIdCancelPost
        //instance.ordersOrderIdCancelPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ordersOrderIdGet', function() {
      it('should call ordersOrderIdGet successfully', function(done) {
        //uncomment below and update the code to test ordersOrderIdGet
        //instance.ordersOrderIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsOrganizationSlugFormsFormTypeFormSlugItemsGet', function() {
      it('should call organizationsOrganizationSlugFormsFormTypeFormSlugItemsGet successfully', function(done) {
        //uncomment below and update the code to test organizationsOrganizationSlugFormsFormTypeFormSlugItemsGet
        //instance.organizationsOrganizationSlugFormsFormTypeFormSlugItemsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsOrganizationSlugFormsFormTypeFormSlugOrdersGet', function() {
      it('should call organizationsOrganizationSlugFormsFormTypeFormSlugOrdersGet successfully', function(done) {
        //uncomment below and update the code to test organizationsOrganizationSlugFormsFormTypeFormSlugOrdersGet
        //instance.organizationsOrganizationSlugFormsFormTypeFormSlugOrdersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsOrganizationSlugItemsGet', function() {
      it('should call organizationsOrganizationSlugItemsGet successfully', function(done) {
        //uncomment below and update the code to test organizationsOrganizationSlugItemsGet
        //instance.organizationsOrganizationSlugItemsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsOrganizationSlugOrdersGet', function() {
      it('should call organizationsOrganizationSlugOrdersGet successfully', function(done) {
        //uncomment below and update the code to test organizationsOrganizationSlugOrdersGet
        //instance.organizationsOrganizationSlugOrdersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
