/**
 * HelloAsso API
 * HelloAsso Open Api specification
 *
 * The version of the OpenAPI document: public
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HelloAssoApi);
  }
}(this, function(expect, HelloAssoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HelloAssoApi.PartenairesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PartenairesApi', function() {
    describe('partnersMeApiClientsPut', function() {
      it('should call partnersMeApiClientsPut successfully', function(done) {
        //uncomment below and update the code to test partnersMeApiClientsPut
        //instance.partnersMeApiClientsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partnersMeApiNotificationsDelete', function() {
      it('should call partnersMeApiNotificationsDelete successfully', function(done) {
        //uncomment below and update the code to test partnersMeApiNotificationsDelete
        //instance.partnersMeApiNotificationsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partnersMeApiNotificationsOrganizationsOrganizationSlugDelete', function() {
      it('should call partnersMeApiNotificationsOrganizationsOrganizationSlugDelete successfully', function(done) {
        //uncomment below and update the code to test partnersMeApiNotificationsOrganizationsOrganizationSlugDelete
        //instance.partnersMeApiNotificationsOrganizationsOrganizationSlugDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partnersMeApiNotificationsOrganizationsOrganizationSlugPut', function() {
      it('should call partnersMeApiNotificationsOrganizationsOrganizationSlugPut successfully', function(done) {
        //uncomment below and update the code to test partnersMeApiNotificationsOrganizationsOrganizationSlugPut
        //instance.partnersMeApiNotificationsOrganizationsOrganizationSlugPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partnersMeApiNotificationsPut', function() {
      it('should call partnersMeApiNotificationsPut successfully', function(done) {
        //uncomment below and update the code to test partnersMeApiNotificationsPut
        //instance.partnersMeApiNotificationsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partnersMeGet', function() {
      it('should call partnersMeGet successfully', function(done) {
        //uncomment below and update the code to test partnersMeGet
        //instance.partnersMeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partnersMeOrganizationsGet', function() {
      it('should call partnersMeOrganizationsGet successfully', function(done) {
        //uncomment below and update the code to test partnersMeOrganizationsGet
        //instance.partnersMeOrganizationsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
